from multiple_models_creation_manager import start_creation_of_machine_learning_models
from config_machine_learning_parameters import get_config_machine_learning_parameters_many
from config_data_parameters import get_config_data_parameters_many
from config_multiple_models_creation_process_parameters import get_config_multiple_models_creation_process_parameters
from bayesian_optimisation_manager import start_bayesian_optimisation_analysis


# Main function
config_data_parameters = get_config_data_parameters_many()
config_machine_learning_parameters = get_config_machine_learning_parameters_many()
config_multiple_models_creation_process_parameters = get_config_multiple_models_creation_process_parameters()

start_creation_of_machine_learning_models(
    config_data_parameters,
    config_machine_learning_parameters,
    config_multiple_models_creation_process_parameters
)

# start_bayesian_optimisation_analysis()
